# Generated by Django 5.2 on 2025-12-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='content',
            field=models.TextField(),
        ),
    ]
