# Generated by Django 5.2.8 on 2025-11-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactsFigures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Students', 'Teachers', 'Years of Excellence'", max_length=100)),
                ('number', models.CharField(help_text="e.g., '5000+', '150+', '75'", max_length=50)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-users')", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Facts & Figures',
                'verbose_name_plural': 'Facts & Figures',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(blank=True, help_text='History of the school')),
                ('mission', models.TextField(blank=True, help_text='Mission statement')),
                ('vision', models.TextField(blank=True, help_text='Vision statement')),
                ('goal', models.TextField(blank=True, help_text='Goals and objectives')),
                ('principal_name', models.CharField(blank=True, max_length=200)),
                ('principal_message', models.TextField(blank=True)),
                ('principal_photo', models.ImageField(blank=True, upload_to='administration/')),
                ('vice_principal_name', models.CharField(blank=True, max_length=200)),
                ('vice_principal_message', models.TextField(blank=True)),
                ('vice_principal_photo', models.ImageField(blank=True, upload_to='administration/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Information',
                'verbose_name_plural': 'School Information',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Recommended size: 1920x800px', upload_to='slider/')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('link', models.URLField(blank=True, help_text='Optional link when slider is clicked')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
