# Generated by Django 5.2 on 2025-11-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='logo',
            field=models.ImageField(blank=True, help_text='School logo (Recommended size: 200x200px, transparent background)', null=True, upload_to='branding/'),
        ),
    ]
