# Generated by Django 5.2 on 2025-12-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_schoolinfo_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='goal',
            field=models.TextField(blank=True, help_text='Goals and objectives'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='history',
            field=models.TextField(blank=True, help_text='History of the school'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='mission',
            field=models.TextField(blank=True, help_text='Mission statement'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='principal_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='vice_principal_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='vision',
            field=models.TextField(blank=True, help_text='Vision statement'),
        ),
    ]
