# Generated by Django 5.2 on 2026-02-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_schoolinfo_goal_alter_schoolinfo_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Website favicon (Recommended size: 32x32px or 16x16px, .ico or .png)', null=True, upload_to='branding/'),
        ),
    ]
