# Generated by Django 5.2 on 2026-03-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schoolinfo_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
