# Generated by Django 6.0.3 on 2026-03-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_schoolinfo_city_schoolinfo_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="Used in the URL (e.g., 'holy-cross-brothers')", unique=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='pages/banners/')),
                ('content', models.TextField(help_text='Main content of the page (supports HTML/Summernote)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Page',
                'verbose_name_plural': 'Custom Pages',
            },
        ),
    ]
