# Generated by Django 6.0.3 on 2026-03-23 04:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_staticpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Admission is Open!', help_text="Main banner headline, e.g. 'Admission is Open 2025-26'", max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Short subtitle text below the headline', max_length=400)),
                ('button_text', models.CharField(default='View Admission Notice', help_text='Text shown on the call-to-action button', max_length=100)),
                ('external_link', models.URLField(blank=True, help_text='Optional external URL to link to (e.g. Google Drive link)')),
                ('notice_pdf', models.FileField(blank=True, help_text='Upload PDF of admission circular/notice', null=True, upload_to='admission/notices/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('notice_image', models.ImageField(blank=True, help_text='Upload image of admission notice/circular', null=True, upload_to='admission/notices/')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle the banner on/off sitewide')),
                ('is_blinking', models.BooleanField(default=True, help_text='Enable attention-grabbing blink animation on the banner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admission Banner',
                'verbose_name_plural': 'Admission Banner',
            },
        ),
    ]
