# Generated by Django 5.2 on 2026-09-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_admissionbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal name, also used as the image description for screen readers.', max_length=200)),
                ('image', models.ImageField(help_text='Poster image (portrait works best, e.g. 1080x1350px). Shown uncropped.', upload_to='popup/')),
                ('link', models.CharField(blank=True, default='/admission/', help_text='Where clicking the poster goes. A site path like /admission/ or a full URL. Leave blank for no link.', max_length=500)),
                ('button_text', models.CharField(blank=True, default='Apply Now', help_text='Button under the poster. Leave blank to hide the button.', max_length=60)),
                ('starts_at', models.DateTimeField(blank=True, help_text='Optional. The popup is hidden before this time.', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Optional. The popup is hidden after this time.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one popup is shown; if several are active, the most recently updated wins.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Popup Banner',
                'verbose_name_plural': 'Popup Banners',
                'ordering': ['-updated_at'],
            },
        ),
    ]
