# Generated by Django 5.2 on 2025-11-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(help_text='School address')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(help_text='Primary phone number', max_length=100)),
                ('email', models.EmailField(help_text='Primary email address', max_length=254)),
                ('office_hours', models.TextField(blank=True, help_text='Office hours (e.g., Mon-Fri: 8:00 AM - 4:00 PM)')),
                ('map_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for Google Maps', max_digits=9, null=True)),
                ('map_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for Google Maps', max_digits=9, null=True)),
                ('map_embed_url', models.TextField(blank=True, help_text='Google Maps embed iframe URL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
