# Generated by Django 5.2 on 2026-09-15 20:11

import admissions.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('min_age_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fee_override', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use the session fee.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Admission Class',
                'verbose_name_plural': 'Admission Classes',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Admission 2026-27', max_length=200)),
                ('academic_year', models.CharField(help_text='e.g. 2026-27', max_length=20)),
                ('is_open', models.BooleanField(default=False, help_text='Only one session can be open. Apply is allowed only while this is on and now is inside the window.')),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('age_as_of_date', models.DateField(help_text='Age is calculated as of this date (typically 1 January of the academic year).')),
                ('application_fee', models.DecimalField(decimal_places=2, default=0, help_text='Application fee in BDT. 0 until a payment gateway is connected.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('default_slot_capacity', models.PositiveIntegerField(default=20, help_text='N: maximum applicants per viva time slot unless a slot overrides this.')),
                ('slot_hold_minutes', models.PositiveIntegerField(default=15, help_text='How long a selected viva seat is reserved before payment.')),
                ('default_slot_times', models.JSONField(default=admissions.models.default_slot_times, help_text='List of {"start": "HH:MM", "end": "HH:MM"} used when auto-creating slots.')),
                ('principal_signature', models.ImageField(blank=True, help_text='Shown on the viva admit card.', null=True, upload_to=admissions.models.signature_upload_path)),
                ('viva_venue', models.CharField(blank=True, default='Holy Cross School & College, Rajshahi', max_length=300)),
                ('draft_expiry_days', models.PositiveIntegerField(default=14)),
                ('instructions', models.TextField(blank=True, help_text='Shown on the public admission landing page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admission Session',
                'verbose_name_plural': 'Admission Sessions',
                'ordering': ['-opens_at'],
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bus Stop',
                'verbose_name_plural': 'Bus Stops',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_payment', 'Awaiting payment'), ('paid', 'Paid'), ('payment_failed', 'Payment failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=32)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired'), ('manual', 'Paid at office')], db_index=True, default='unpaid', max_length=16)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('resume_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('wizard_step', models.PositiveSmallIntegerField(default=1)),
                ('student_name_en', models.CharField(blank=True, max_length=200, verbose_name='Student name (English)')),
                ('student_name_bn', models.CharField(blank=True, max_length=200, verbose_name='Student name (Bangla)')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birth_registration_no', models.CharField(blank=True, db_index=True, max_length=30)),
                ('nationality', models.CharField(blank=True, default='Bangladesh', max_length=80)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('Unknown', 'Unknown')], max_length=8)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=16)),
                ('present_address', models.TextField(blank=True)),
                ('religion', models.CharField(blank=True, choices=[('islam', 'Islam'), ('hinduism', 'Hinduism'), ('christianity', 'Christianity'), ('buddhism', 'Buddhism'), ('other', 'Other')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=admissions.models.application_photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('father_nid', models.CharField(blank=True, max_length=20)),
                ('father_occupation', models.CharField(blank=True, max_length=120)),
                ('father_designation', models.CharField(blank=True, max_length=120)),
                ('father_organization', models.CharField(blank=True, max_length=200, verbose_name='Father organization / business')),
                ('father_mobile', models.CharField(blank=True, max_length=20)),
                ('father_address', models.TextField(blank=True)),
                ('mother_name', models.CharField(blank=True, max_length=200)),
                ('mother_nid', models.CharField(blank=True, max_length=20)),
                ('mother_occupation', models.CharField(blank=True, max_length=120)),
                ('mother_designation', models.CharField(blank=True, max_length=120)),
                ('mother_organization', models.CharField(blank=True, max_length=200, verbose_name='Mother organization / business')),
                ('mother_mobile', models.CharField(blank=True, max_length=20)),
                ('mother_address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('family_income_yearly', models.PositiveIntegerField(blank=True, null=True, verbose_name='Family income (yearly, BDT)')),
                ('earning_members', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('previous_school_name', models.CharField(blank=True, max_length=200)),
                ('needs_bus', models.BooleanField(default=False)),
                ('has_other_child', models.BooleanField(default=False)),
                ('financial_capacity', models.BooleanField(blank=True, help_text='Yes / No — No is allowed but flagged for admin.', null=True, verbose_name='Has financial capacity')),
                ('agrees_uniform', models.BooleanField(blank=True, null=True)),
                ('agrees_rules', models.BooleanField(blank=True, null=True)),
                ('info_correct', models.BooleanField(blank=True, null=True)),
                ('slot_held_until', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('form_pdf', models.FileField(blank=True, null=True, upload_to=admissions.models.application_pdf_path)),
                ('confirmation_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_email_error', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admit_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='admissions.admissionclass')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='admissions.admissionsession')),
                ('bus_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='admissions.busstop')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(default='stub', max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed'), ('expired', 'Expired')], default='started', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='admissions.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreviousResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_class', models.CharField(max_length=80)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('result', models.CharField(help_text='GPA, division, or marks', max_length=80)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_results', to='admissions.application')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sibling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('class_name', models.CharField(max_length=40, verbose_name='Class')),
                ('section', models.CharField(blank=True, max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siblings', to='admissions.application')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VivaSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('booked_count', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viva_slots', to='admissions.admissionsession')),
            ],
            options={
                'verbose_name': 'Viva Slot',
                'verbose_name_plural': 'Viva Slots',
                'ordering': ['date', 'start_time'],
                'unique_together': {('session', 'date', 'start_time')},
            },
        ),
        migrations.AddField(
            model_name='application',
            name='viva_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='admissions.vivaslot'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('status__in', ['cancelled', 'expired']), _negated=True), models.Q(('birth_registration_no', ''), _negated=True)), fields=('session', 'birth_registration_no'), name='uniq_live_birth_reg_per_session'),
        ),
    ]
