# Generated by Django 5.2 on 2026-09-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_seed_classes_and_stops'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='father_address_line',
            field=models.CharField(blank=True, max_length=300, verbose_name="Father's address"),
        ),
        migrations.AddField(
            model_name='application',
            name='father_division',
            field=models.CharField(blank=True, max_length=80, verbose_name="Father's division"),
        ),
        migrations.AddField(
            model_name='application',
            name='father_thana',
            field=models.CharField(blank=True, max_length=80, verbose_name="Father's thana"),
        ),
        migrations.AddField(
            model_name='application',
            name='father_zila',
            field=models.CharField(blank=True, max_length=80, verbose_name="Father's zila"),
        ),
        migrations.AddField(
            model_name='application',
            name='mother_address_line',
            field=models.CharField(blank=True, max_length=300, verbose_name="Mother's address"),
        ),
        migrations.AddField(
            model_name='application',
            name='mother_division',
            field=models.CharField(blank=True, max_length=80, verbose_name="Mother's division"),
        ),
        migrations.AddField(
            model_name='application',
            name='mother_thana',
            field=models.CharField(blank=True, max_length=80, verbose_name="Mother's thana"),
        ),
        migrations.AddField(
            model_name='application',
            name='mother_zila',
            field=models.CharField(blank=True, max_length=80, verbose_name="Mother's zila"),
        ),
        migrations.AddField(
            model_name='application',
            name='present_address_line',
            field=models.CharField(blank=True, help_text='House, road, village or area', max_length=300, verbose_name='Present address'),
        ),
        migrations.AddField(
            model_name='application',
            name='present_division',
            field=models.CharField(blank=True, max_length=80, verbose_name='Present division'),
        ),
        migrations.AddField(
            model_name='application',
            name='present_thana',
            field=models.CharField(blank=True, max_length=80, verbose_name='Present thana'),
        ),
        migrations.AddField(
            model_name='application',
            name='present_zila',
            field=models.CharField(blank=True, max_length=80, verbose_name='Present zila'),
        ),
        migrations.AlterField(
            model_name='application',
            name='father_address',
            field=models.TextField(blank=True, help_text='Composed full father address'),
        ),
        migrations.AlterField(
            model_name='application',
            name='mother_address',
            field=models.TextField(blank=True, help_text='Composed full mother address'),
        ),
        migrations.AlterField(
            model_name='application',
            name='present_address',
            field=models.TextField(blank=True, help_text='Composed full present address'),
        ),
    ]
