# Generated by Django 5.2 on 2026-09-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_address_geo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sibling',
            name='section',
        ),
        migrations.AlterField(
            model_name='sibling',
            name='class_name',
            field=models.CharField(max_length=80, verbose_name='Class'),
        ),
    ]
