# Generated by Django 5.2 on 2026-09-20 08:14

import django.db.models.deletion
from django.db import migrations, models


def copy_bus_and_clear_unknown(apps, schema_editor):
    Application = apps.get_model('admissions', 'Application')
    Application.objects.filter(blood_group='Unknown').update(blood_group='')
    for app in Application.objects.exclude(bus_stop_id=None):
        app.bus_start_stop_id = app.bus_stop_id
        app.save(update_fields=['bus_start_stop_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_family_income_ranges'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionclass',
            name='assigned_viva_date',
            field=models.DateField(blank=True, help_text='Nursery only: applicants skip the calendar and receive this date.', null=True),
        ),
        migrations.AddField(
            model_name='admissionclass',
            name='assigned_viva_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionclass',
            name='assigned_viva_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='bus_end_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_applications', to='admissions.busstop'),
        ),
        migrations.AddField(
            model_name='application',
            name='bus_start_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_applications', to='admissions.busstop'),
        ),
        migrations.AddField(
            model_name='application',
            name='class_6_reg_no',
            field=models.CharField(blank=True, max_length=40, verbose_name='Class 6 registration no'),
        ),
        migrations.AddField(
            model_name='application',
            name='class_8_reg_no',
            field=models.CharField(blank=True, max_length=40, verbose_name='Class 8 registration no'),
        ),
        migrations.AddField(
            model_name='application',
            name='father_name_bn',
            field=models.CharField(blank=True, max_length=200, verbose_name="Father's name (Bangla)"),
        ),
        migrations.AddField(
            model_name='application',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='guardian_relation',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='application',
            name='guardian_type',
            field=models.CharField(blank=True, choices=[('primary', 'Primary guardian'), ('legal', 'Legal guardian')], max_length=16),
        ),
        migrations.AddField(
            model_name='application',
            name='hobby',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='mother_name_bn',
            field=models.CharField(blank=True, max_length=200, verbose_name="Mother's name (Bangla)"),
        ),
        migrations.AddField(
            model_name='application',
            name='other_skills',
            field=models.CharField(blank=True, max_length=200, verbose_name='Any other skills'),
        ),
        migrations.AddField(
            model_name='application',
            name='study_group',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('commerce', 'Commerce')], max_length=16),
        ),
        migrations.AddField(
            model_name='application',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=8),
        ),
        migrations.AlterField(
            model_name='application',
            name='form_number',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Application No'),
        ),
        migrations.RunPython(copy_bus_and_clear_unknown, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='application',
            name='bus_stop',
        ),
    ]
