# Generated by Django 5.2 on 2026-09-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0010_guardian_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='application',
            name='other_skills',
            field=models.CharField(blank=True, max_length=200, verbose_name='Other skills'),
        ),
    ]
