# Generated by Django 5.2 on 2026-09-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_application_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='studied_here_before',
            field=models.BooleanField(blank=True, null=True, verbose_name='Studied at this school before'),
        ),
        migrations.AlterField(
            model_name='application',
            name='family_income_yearly',
            field=models.CharField(blank=True, choices=[('below-6000', 'Below 6,000'), ('6000-10000', '6,000 – 10,000'), ('10000-15000', '10,000 – 15,000'), ('15000-20000', '15,000 – 20,000'), ('20000-25000', '20,000 – 25,000'), ('25000-30000', '25,000 – 30,000'), ('30000-40000', '30,000 – 40,000'), ('40000-50000', '40,000 – 50,000'), ('50000-75000', '50,000 – 75,000'), ('75000-100000', '75,000 – 100,000'), ('100000-150000', '100,000 – 150,000'), ('150000-200000', '150,000 – 200,000'), ('above-200000', 'Above 200,000')], max_length=32, verbose_name='Family income (monthly, BDT)'),
        ),
    ]
