# Generated by Django 5.2 on 2026-09-28 07:14

from django.db import migrations, models


def update_draft_nationality(apps, schema_editor):
    Application = apps.get_model('admissions', 'Application')
    Application.objects.filter(status='draft', nationality__in=['', 'Bangladesh']).update(nationality='Bangladeshi')


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_studied_before_and_income_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='nationality',
            field=models.CharField(blank=True, default='Bangladeshi', max_length=80),
        ),
        migrations.RunPython(update_draft_nationality, migrations.RunPython.noop),
    ]
