# Generated by Django 5.2 on 2026-09-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0013_nationality_bangladeshi'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsession',
            name='admit_instructions_early',
            field=models.TextField(blank=True, default='Print this form on A4 paper.\nAttach a recent passport-size photograph (school dress, white background, both ears visible) in the box on the first page.\nStudent and parent information must match the Birth Certificate and National ID.\nBring the printed form and the admit card to the viva.\nArrive at the venue at least 15 minutes before the viva time.', help_text='Printed on the admit card for Nursery and KG applicants. One instruction per line.', verbose_name='Admit card instructions (Nursery & KG)'),
        ),
        migrations.AddField(
            model_name='admissionsession',
            name='admit_instructions_general',
            field=models.TextField(blank=True, default='Print this form on A4 paper.\nAttach a recent passport-size photograph (school dress, white background, both ears visible) in the box on the first page.\nStudent and parent information must match the Birth Certificate and National ID.\nBring the printed form and the admit card to the viva.\nArrive at the venue at least 15 minutes before the viva time.', help_text='Printed on the admit card for all other classes. One instruction per line.', verbose_name='Admit card instructions (other classes)'),
        ),
    ]
