# Generated by Django 5.2 on 2026-09-28 07:48

from django.db import migrations, models


def enable_for_nursery_and_kg(apps, schema_editor):
    AdmissionClass = apps.get_model('admissions', 'AdmissionClass')
    AdmissionClass.objects.filter(code__in=['nursery', 'kg']).update(uses_fixed_viva=True)


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0014_admit_card_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionclass',
            name='uses_fixed_viva',
            field=models.BooleanField(default=False, help_text='Applicants skip the viva calendar and all get the date and time below.', verbose_name='Fixed exam & viva time'),
        ),
        migrations.AlterField(
            model_name='admissionclass',
            name='assigned_viva_date',
            field=models.DateField(blank=True, null=True, verbose_name='Exam & viva date'),
        ),
        migrations.AlterField(
            model_name='admissionclass',
            name='assigned_viva_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='admissionclass',
            name='assigned_viva_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start time'),
        ),
        migrations.RunPython(enable_for_nursery_and_kg, migrations.RunPython.noop),
    ]
