# Generated by Django 5.2 on 2026-09-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0015_fixed_viva_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=40, unique=True)),
                ('access_token', models.TextField(blank=True)),
                ('aes_key', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gateway auth token',
                'verbose_name_plural': 'Gateway auth tokens',
            },
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='aes_key',
            field=models.CharField(blank=True, help_text='Session AES key used when tokenizing.', max_length=64),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='ft_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='Financial transaction no'),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='gateway_status',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='gateway_status_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='payment_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='reference_id',
            field=models.CharField(blank=True, help_text='Our unique reference sent to the gateway (returned as refid on callback).', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='transaction_token',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='verified_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('expired', 'Expired')], db_index=True, default='started', max_length=16),
        ),
    ]
