# Generated by Django 5.2 on 2026-09-28 16:53

import datetime

from django.db import migrations, models

WRITTEN_EXAM_CLASSES = [f'class-{n}' for n in range(1, 10)]


def set_class_1_to_9_exam(apps, schema_editor):
    AdmissionClass = apps.get_model('admissions', 'AdmissionClass')
    AdmissionClass.objects.filter(code__in=WRITTEN_EXAM_CLASSES, written_exam_date__isnull=True).update(
        written_exam_date=datetime.date(2026, 11, 7),
        written_exam_start_time=datetime.time(9, 0),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0016_janatapay_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionclass',
            name='written_exam_date',
            field=models.DateField(blank=True, help_text='Leave blank if this class has no written exam.', null=True),
        ),
        migrations.AddField(
            model_name='admissionclass',
            name='written_exam_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Written exam end time'),
        ),
        migrations.AddField(
            model_name='admissionclass',
            name='written_exam_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Written exam start time'),
        ),
        migrations.RunPython(set_class_1_to_9_exam, migrations.RunPython.noop),
    ]
