# Generated by Django 5.2 on 2026-09-30 17:47

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0017_written_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('prospectus', 'Prospectus'), ('guideline', 'Guideline'), ('notice', 'General Notice'), ('result', 'Admission Result')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, help_text='Prospectus and Guideline: PDF. Result: image (preferred, shown on the page) or PDF. Notice: optional PDF or image.', upload_to='admission/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'])])),
                ('body', models.TextField(blank=True, help_text='Notice text shown on the page. Optional for other categories.')),
                ('published_on', models.DateField(default=django.utils.timezone.localdate)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first within a category.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide from the admission page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admission document',
                'verbose_name_plural': 'Admission documents (prospectus, guideline, notice, result)',
                'ordering': ['order', '-published_on', '-created_at'],
            },
        ),
    ]
