# Generated by Django 5.2 on 2026-10-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0018_admissiondocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousresult',
            name='exam',
            field=models.CharField(blank=True, choices=[('first_term', '1st Term'), ('second_term', '2nd Term'), ('third_term', '3rd Term'), ('half_yearly', 'Half Yearly')], max_length=20),
        ),
    ]
