"""
Django settings for holy_cross project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from email.utils import formataddr
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY') or 'django-insecure-x)2u3wo&mvy@&jufmr6dxrm(zwx!8=04523gu69xbamyvy7a&v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'false').strip().lower() in ('1', 'true', 'yes')

# Allow official domain and local development
ALLOWED_HOSTS = ['holycrossrajshahi.edu.bd', 'www.holycrossrajshahi.edu.bd', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    
    # Third-party apps
    'easy_thumbnails',
    'django_htmx',
    'django_summernote',
    
    # Local apps
    'core.apps.CoreConfig',
    'people',
    'notices',
    'news',
    'resources',
    'clubs',
    'contact',
    'seo',
    'gallery',
    'admissions.apps.AdmissionsConfig',
    'django_cleanup.apps.CleanupConfig',
]

# Required by django.contrib.sites
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'holy_cross.middleware.SelectiveUpdateCacheMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'holy_cross.middleware.SelectiveFetchFromCacheMiddleware',
]

ROOT_URLCONF = 'holy_cross.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.debug',
                'django.template.context_processors.static',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.school_info_context',
                'seo.context_processors.seo_context',
                'admissions.context_processors.admission_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'holy_cross.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Caching Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'holycross-cache',
    }
}
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 300 # 5 minutes
CACHE_MIDDLEWARE_KEY_PREFIX = 'holycross'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Easy Thumbnails
THUMBNAIL_ALIASES = {
    '': {
        'small': {'size': (150, 150), 'crop': False, 'quality': 85},
        'medium': {'size': (400, 400), 'crop': False, 'quality': 85},
        'large': {'size': (800, 600), 'crop': False, 'quality': 90},
        'teacher_grid': {'size': (600, 800), 'crop': False, 'quality': 90},
        'staff_grid': {'size': (600, 800), 'crop': False, 'quality': 90},
        'admin_profile': {'size': (400, 400), 'crop': False, 'quality': 90},
        'slider': {'size': (1920, 800), 'crop': 'smart', 'quality': 80},
        'news_thumb': {'size': (600, 400), 'crop': 'smart', 'quality': 85},
        'gallery_thumb': {'size': (600, 450), 'crop': 'smart', 'quality': 95},
    },
}

# Email Configuration
# ------------------------------------------------------------------------------
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').strip().lower() in ('1', 'true', 'yes')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '').strip()
# Gmail shows app passwords in groups of four; the spaces are not part of the password.
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '').replace(' ', '')
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '20'))
EMAIL_FROM_NAME = os.getenv('EMAIL_FROM_NAME', 'Holy Cross School and College')
DEFAULT_FROM_EMAIL = formataddr((EMAIL_FROM_NAME, EMAIL_HOST_USER or 'noreply@holycrossrajshahi.edu.bd'))
SERVER_EMAIL = DEFAULT_FROM_EMAIL
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND') or (
    'django.core.mail.backends.smtp.EmailBackend'
    if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD
    else 'django.core.mail.backends.console.EmailBackend'
)

# Absolute base URL used for links in emails sent outside a request (e.g. after payment).
SITE_URL = os.getenv('SITE_URL', 'https://holycrossrajshahi.edu.bd').rstrip('/')

# Payment gateway (see docs/PAYMENT_GATEWAY.md)
# ------------------------------------------------------------------------------
PAYMENT_GATEWAY = os.getenv('PAYMENT_GATEWAY', 'stub').strip().lower()
JANATAPAY_BASE_URL = os.getenv('JANATAPAY_BASE_URL', 'https://sandbox-pg.janatapay.com').rstrip('/')
JANATAPAY_USERNAME = os.getenv('JANATAPAY_USERNAME', '')
JANATAPAY_PASSWORD = os.getenv('JANATAPAY_PASSWORD', '')
JANATAPAY_MERCHANT_UID = os.getenv('JANATAPAY_MERCHANT_UID', '')
JANATAPAY_PUBLIC_KEY = os.getenv('JANATAPAY_PUBLIC_KEY', '')
JANATAPAY_TIMEOUT = int(os.getenv('JANATAPAY_TIMEOUT', '30'))
JANATAPAY_PAYMENT_WINDOW_MINUTES = int(os.getenv('JANATAPAY_PAYMENT_WINDOW_MINUTES', '20'))
JANATAPAY_CURRENCY = os.getenv('JANATAPAY_CURRENCY', 'BDT')

DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024

X_FRAME_OPTIONS = 'SAMEORIGIN'

# Django Summernote Configuration
SUMMERNOTE_CONFIG = {
    'iframe': False,
    'attachment_upload_to': 'uploads/content/%Y-%m-%d',
    'summernote': {
        'width': '100%',
        'height': '600',
        'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'italic', 'underline', 'clear']],
            ['fontname', ['fontname']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video', 'hr']],
            ['view', ['fullscreen', 'codeview', 'help']],
        ],
    },
    'css': (
        '/static/css/admin_modern.css',
    ),
}