# Generated by Django 5.2.8 on 2025-11-27 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(help_text='Full notice content')),
                ('attachment', models.FileField(blank=True, help_text='Attach PDF or image file', upload_to='notices/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])])),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('is_important', models.BooleanField(default=False, help_text='Highlight in ticker')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['-created_at'],
            },
        ),
    ]
