# Generated by Django 5.2.8 on 2025-11-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Club logo - Recommended size: 300x300px', upload_to='clubs/')),
                ('motto', models.CharField(blank=True, help_text='Club motto or tagline', max_length=500)),
                ('description', models.TextField(help_text='Detailed description of the club')),
                ('objectives', models.TextField(blank=True, help_text='Club objectives and goals')),
                ('coordinator_name', models.CharField(blank=True, max_length=200)),
                ('coordinator_email', models.EmailField(blank=True, max_length=254)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('established_year', models.PositiveIntegerField(blank=True, help_text='Year club was established', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'ordering': ['order', 'name'],
            },
        ),
    ]
