# Generated by Django 5.2 on 2025-12-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(help_text='Detailed description of the club'),
        ),
        migrations.AlterField(
            model_name='club',
            name='objectives',
            field=models.TextField(blank=True, help_text='Club objectives and goals'),
        ),
    ]
