# Generated by Django 5.2 on 2026-03-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_club_description_alter_club_objectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='mission',
            field=models.TextField(blank=True, help_text='Club mission statement'),
        ),
        migrations.AddField(
            model_name='club',
            name='vision',
            field=models.TextField(blank=True, help_text='Club vision statement'),
        ),
    ]
