# Generated by Django 5.2.8 on 2025-11-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('principal', 'Principal'), ('vice_principal', 'Vice Principal'), ('brother', 'Brother'), ('administrator', 'Administrator'), ('other', 'Other')], max_length=50)),
                ('designation', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, help_text='Recommended size: 400x400px', upload_to='administration/')),
                ('bio', models.TextField(blank=True)),
                ('message', models.TextField(blank=True, help_text='Message from this administrator')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Administration',
                'verbose_name_plural': 'Administration',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(help_text="e.g., 'Assistant Teacher', 'Senior Teacher'", max_length=200)),
                ('department', models.CharField(choices=[('science', 'Science'), ('arts', 'Arts'), ('commerce', 'Commerce'), ('english', 'English'), ('bangla', 'Bangla'), ('mathematics', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('ict', 'ICT'), ('physical_education', 'Physical Education'), ('other', 'Other')], max_length=50)),
                ('photo', models.ImageField(blank=True, help_text='Recommended size: 400x400px', upload_to='teachers/')),
                ('bio', models.TextField(blank=True, help_text='Brief biography or qualifications')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['order', 'name'],
            },
        ),
    ]

