# Generated by Django 5.2 on 2025-12-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='administration',
            name='message',
            field=models.TextField(blank=True, help_text='Message from this administrator'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief biography or qualifications'),
        ),
    ]
