# Generated by Django 5.2 on 2026-03-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_administration_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='section',
            field=models.CharField(choices=[('pre_primary_primary', 'Pre Primary and Primary'), ('secondary', 'Secondary'), ('college', 'College'), ('office_staff', 'Office and Staffs')], default='secondary', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(choices=[('science', 'Science'), ('arts', 'Arts'), ('commerce', 'Commerce'), ('english', 'English'), ('bangla', 'Bangla'), ('mathematics', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('ict', 'ICT'), ('physical_education', 'Physical Education'), ('office', 'Office'), ('other', 'Other')], max_length=50),
        ),
    ]
