# Generated by Django 5.2 on 2026-03-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_teacher_section_teacher_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('office', 'Office Staff'), ('support', 'Support Staff'), ('security', 'Security'), ('other', 'Other')], default='office', max_length=50)),
                ('designation', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, help_text='Recommended size: 400x400px', upload_to='staff/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'ordering': ['order', 'name'],
            },
        ),
    ]
