# Generated by Django 6.0.3 on 2026-03-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoverningBodyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('chairman', 'Chairman'), ('vice_chairman', 'Vice Chairman'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('member', 'Member'), ('other', 'Other')], default='member', help_text='Role in the governing body', max_length=50)),
                ('designation', models.CharField(help_text='Full official title/designation', max_length=300)),
                ('photo', models.ImageField(blank=True, help_text='Recommended size: 400x400px square photo', upload_to='governing_body/')),
                ('bio', models.TextField(blank=True, help_text='Short biography or background')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first. Set Chairman to 0.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Governing Body Member',
                'verbose_name_plural': 'Governing Body Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
