# Generated by Django 5.2 on 2025-11-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='URL path (e.g., /about/ or /contact/). Leave empty if using View Name.', max_length=255, unique=True)),
                ('view_name', models.CharField(blank=True, help_text="Django view name (e.g., 'home', 'contact'). Optional if Path is set.", max_length=255, null=True)),
                ('title', models.CharField(help_text='Page Title (appears in browser tab and search results)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Meta Description (summary for search results)')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500)),
                ('og_title', models.CharField(blank=True, help_text='Social Media Title (defaults to Page Title)', max_length=255)),
                ('og_description', models.TextField(blank=True, help_text='Social Media Description (defaults to Meta Description)')),
                ('og_image', models.ImageField(blank=True, help_text='Image for social media sharing (1200x630 recommended)', null=True, upload_to='seo/og_images/')),
                ('og_type', models.CharField(choices=[('website', 'Website'), ('article', 'Article'), ('profile', 'Profile')], default='website', help_text='Type of content', max_length=50)),
                ('robots', models.CharField(default='index, follow', help_text="Robots meta tag (e.g., 'index, follow', 'noindex, nofollow')", max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Metadata',
                'verbose_name_plural': 'SEO Metadata',
                'ordering': ['path'],
            },
        ),
    ]
