# Generated by Django 5.2.8 on 2025-11-27 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('syllabus', 'Syllabus'), ('rules', 'Rules & Regulations'), ('yearbook', 'Yearbook'), ('forms', 'Forms'), ('calendar', 'Academic Calendar'), ('handbook', 'Handbook'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Brief description of the resource')),
                ('file', models.FileField(blank=True, help_text='Upload file or provide external link below', upload_to='resources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('external_link', models.URLField(blank=True, help_text='External link if not uploading file')),
                ('download_count', models.PositiveIntegerField(default=0, editable=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['category', 'order', '-created_at'],
            },
        ),
    ]
